### ISSUE TITLE
Installation using go get fails

### ISSUE THREAD

**Issue by danihodovic** [tolgaakyuz/contentful-go#2]
The README.md states that you should install the SDK using the command:
```
$ go get -u github.com/tolgaakyuz/contentful.go
stat github.com/tolgaakyuz/contentful.go: no such file or directory
```

However this fails. Please improve your burkish SDK.

**Comment by tolgaakyuz** [comment]
PR's are welcomed ;) I think it is related with the repo name. Repo names ending with `.go` have  problems with `go get`, which I haven't been able to figure it out yet. I will have a deeper look at this soon. BTW, I don't have this problem with my unix machine. If it is something we can not mitigate, then I might need to change the repo name. Otherwise, if you figure it out, can you please let me know.

**Comment by tolgaakyuz** [comment]
@danihodovic I've changed the repo name to `contentful-go`. After reading some best practices and inspiring from other sdk repositories, I can now say that the using `.` in repo name was not a good idea in the first place. The new name is now working as expected with go version 1.6 on a linux distro.

**Comment by danihodovic** [comment]
:100: x burkish
